### ISSUE TITLE
单数据配置没事，但是我配置了主从配置就不行了

### ISSUE THREAD

**Issue by hcr707305003** [webman-tech/debugbar#10]
![image](https://github.com/webman-tech/debugbar/assets/22547038/ce05bb1f-a310-40d6-88f6-f0f3568c225a)

**Comment by krissss** [comment]
麻烦提供具体的配置和复现步骤，看这提示好像是网络问题

**Comment by hcr707305003** [comment]
> 麻烦提供具体的配置和复现步骤，看这提示好像是网络问题

composer未引用插件时
![image](https://github.com/webman-tech/debugbar/assets/22547038/93b46a0c-aeff-4632-9886-92a6439e0138)
引用后
![image](https://github.com/webman-tech/debugbar/assets/22547038/8fecc710-a6fa-4e08-a100-3202e7022838)
![image](https://github.com/webman-tech/debugbar/assets/22547038/a977f94d-6b90-4cbf-af7a-4c5bd4620cb3)
这个方式是按照thinkorm配置使用的
![image](https://github.com/webman-tech/debugbar/assets/22547038/7ba19cce-c6c3-476b-a2eb-74abc26e194b)

**Comment by krissss** [comment]
已支持，更新下
