### ISSUE TITLE
是否可以更新php版本,最低支持7.3

### ISSUE THREAD

**Issue by evilk123** [webman-tech/debugbar#3]
非常感谢老哥的这个包,很好用,很赞,谢谢
但我们的PHP版本是7.3
请问,是否可以降低PHP最低版本到7.3?

**Comment by krissss** [comment]
这个需要评估，主要要类属性类型上，看后面的情况吧

**Comment by evilk123** [comment]
> 这个需要评估，主要要类属性类型上，看后面的情况吧

好的,谢谢

**Comment by krissss** [comment]
更新到 1.4 版本试一下
