### ISSUE TITLE
使用vscode 远程开发的时候访问记录异常

### ISSUE THREAD

**Issue by yun3948** [webman-tech/debugbar#6]
你好，我因为特殊原因代码在服务器，使用vscode 远程开发，开发时候本地访问的 路径为为 localhost:8787 ，此时无法记录访问历史，全是 undefined，不知道是哪里出的问题，麻烦有空的话可以看下

**Comment by krissss** [comment]
没有太明白使用场景，能给一些具体的信息吗
webman 启动后的日志
访问 localhost:8787 后浏览器的展示，以及 console 下 network 里的信息
哪里显示的 undefined 的信息

**Comment by yun3948** [comment]
刚才测试了一下，发现我用nginx 代理以后，host/_debugbar/sample   访问不显示底部的 debug 栏，资源加载错误了，这个等下我研究下。上面的问题访问的地址是 localhost:8787/_debugbar/sample ,用正常域名访问同一个地址，第一次正常，然后多访问几次以后，点击 showall 就会出现下图，不知道是不是开发环境影响导致的

![image](https://user-images.githubusercontent.com/12403724/220516711-ea35fd7e-09eb-44c3-a297-01dec1d9797e.png)

**Comment by krissss** [comment]
php 什么版本的

**Comment by yun3948** [comment]
php 版本是 8.0.26

**Comment by krissss** [comment]
https://github.com/webman-tech/debugbar/issues/2#issuecomment-1238984986
参考这边后面的方式排查一下呢

**Comment by yun3948** [comment]
我刚才看了下，是同一个错误 。看来只能等后续修复把。

**Comment by krissss** [comment]
现在应该修复了的，我看已经发版本了，更新下 `maximebf/debugbar`

`composer require webman-tech/debugbar --dev -W`

**Comment by yun3948** [comment]
貌似不行。刚才 remove 然后 重新执行 你发的命令 ，重启webman ，日志还是一样的错误

**Comment by krissss** [comment]
看下版本  `composer info maximebf/debugbar`
是不是用了 阿里云 packagist 镜像，是的话去掉

**Comment by yun3948** [comment]
去掉阿里云重新执行了一遍可以了，十分感谢
