### ISSUE TITLE
没有记录信息

### ISSUE THREAD

**Issue by yun3948** [webman-tech/debugbar#7]
能不能麻烦问下，我这边是通过token  访问的接口。 记录里面看不到执行的SQL记录
![image](https://user-images.githubusercontent.com/12403724/221200541-84b97144-e9d1-434e-80d1-c833fbee4edc.png)

**Comment by krissss** [comment]
能提供一下具体的信息吗
或者最小化的一个复现的例子

**Comment by yun3948** [comment]
抱歉啊。 刚才试了一下最新安装的， 就执行了一下几个步骤， webman 的安装 ，数据库的操作安装，env 的插件， 然后就是 debugbar 插件，也是无法记录的，猜测是不是laravel 组件更新版本了。 导致失效了。我本地php版本8.1 的

**Comment by krissss** [comment]
就没有数据库的记录吗，其他信息都有？laravel 的 db 什么版本的

**Comment by yun3948** [comment]
刚才看了一下 ，Route 里面显示路由的话路由会有信息，默认路由的话就没有信息了，其他应该都是正常的可以记录
  db versions : * v9.52.4 ，下面是DB 信息截图   
![image](https://user-images.githubusercontent.com/12403724/221733119-226454bf-7629-483c-9748-b6182356ebde.png)
昨天全新安装的话版本记得是10.x

**Comment by krissss** [comment]
麻烦把 `config/database.php` 里的 default 参数改成 default（原来是 mysql）试下
如：
```php
// 默认数据库
'default' => 'default', // 改这里

// 各种数据库配置
'connections' => [
    'default' => [ // 改这里
          'driver'      => 'mysql',
          // 其他参数
    ],
],
```

**Comment by krissss** [comment]
更新一下 2.1.1 版本，应该修复了

**Comment by yun3948** [comment]
刚才测试，修改了一下配置文件确实可以了， 感谢大佬
