### ISSUE TITLE
请问orm只支持Laravel的么.LaravelDb不显示.

### ISSUE THREAD

**Issue by zjttfs** [webman-tech/debugbar#9]
现在项目用的[think-orm](https://www.workerman.net/plugin/14#%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20think-orm%E6%8F%92%E4%BB%B6%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)

现在里面只有mongodb的信息
![image](https://github.com/webman-tech/debugbar/assets/24729880/dbac3092-8a0a-4820-83a8-a3c054e32a2c)
![image](https://github.com/webman-tech/debugbar/assets/24729880/4afd0327-1ad4-4ccb-b865-a30a1ba1252b)

**Comment by krissss** [comment]
目前确实不支持think orm
欢迎PR

**Comment by zjttfs** [comment]
感谢回复,没有用过这个组件. 我先了解下.

**Comment by krissss** [comment]
更新到 2.2.0 已支持

**Comment by zjttfs** [comment]
大佬厉害了.
